#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  certificate:

services:
  ca.academy.certificate.com:
    image: hyperledger/fabric-ca:1.4.0
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.academy.certificate.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.academy.certificate.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/be10679a040bf6a3f1ac941bfa76d52de26d20d8f216030ac82aa1097f284eec_sk
    ports:
      - '7054:7054'
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.academy.certificate.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/be10679a040bf6a3f1ac941bfa76d52de26d20d8f216030ac82aa1097f284eec_sk -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/academy.certificate.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.academy.certificate.com
    networks:
      - certificate

  ca.student.certificate.com:
    image: hyperledger/fabric-ca:1.4.0
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.student.certificate.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.student.certificate.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/de3f2a6cd362767339d752f76f59f1c91790216ab878570897ba90c7548073c5_sk
    ports:
      - '8054:7054'
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.student.certificate.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/de3f2a6cd362767339d752f76f59f1c91790216ab878570897ba90c7548073c5_sk -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/student.certificate.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.student.certificate.com
    networks:
      - certificate

  orderer.certificate.com:
    container_name: orderer.certificate.com
    image: hyperledger/fabric-orderer:1.4.0
    environment:
      - FABRIC_LOGGING_SPEC=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - '7050:7050'
    volumes:
      - ./channel-artifacts/:/etc/hyperledger/configtx
      - ./crypto-config/ordererOrganizations/certificate.com/orderers/orderer.certificate.com/:/etc/hyperledger/orderer
    networks:
      - certificate

  peer0.academy.certificate.com:
    container_name: peer0.academy.certificate.com
    image: hyperledger/fabric-peer:1.4.0
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.academy.certificate.com
      - FABRIC_LOGGING_SPEC=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=AcademyMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer0.academy.certificate.com:7051
      # # the following setting starts chaincode containers on the same
      # # bridge network as the peers
      # # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_certificate
      # Use by explorer
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.academy.certificate.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.academy.certificate.com:7051
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - '7051:7051'
      - '7053:7053'
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/academy.certificate.com/peers/peer0.academy.certificate.com/msp:/etc/hyperledger/msp/peer
      - ./crypto-config/peerOrganizations/academy.certificate.com/users:/etc/hyperledger/msp/users
      - ./channel-artifacts:/etc/hyperledger/configtx
    networks:
      - certificate

  peer0.student.certificate.com:
    container_name: peer0.student.certificate.com
    image: hyperledger/fabric-peer:1.4.0
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.student.certificate.com
      - FABRIC_LOGGING_SPEC=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=StudentMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer0.student.certificate.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_certificate
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.student.certificate.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.student.certificate.com:7051
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - '8051:7051'
      - '8053:7053'
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/student.certificate.com/peers/peer0.student.certificate.com/msp:/etc/hyperledger/msp/peer
      - ./crypto-config/peerOrganizations/student.certificate.com/users:/etc/hyperledger/msp/users
      - ./channel-artifacts:/etc/hyperledger/configtx
    networks:
      - certificate

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:1.4.0
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.academy.certificate.com:7051
      - CORE_PEER_LOCALMSPID=AcademyMSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/academy.certificate.com/users/Admin@academy.certificate.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./../database:/opt/gopath/src/github.com/chaincode
      - $GOPATH/src/github.com/hyperledger:/opt/gopath/src/github.com/hyperledger
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
      - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
    networks:
      - certificate
